# Generated by Django 4.2.16 on 2025-01-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='time_label',
            field=models.CharField(blank=True, help_text='Event time eg. 1:00pm - 5:15pm', null=True),
        ),
    ]
