# Generated by Django 4.2.16 on 2025-01-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_events_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
