# Generated by Django 4.2.16 on 2025-01-13 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_events_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='published_date',
        ),
    ]
