# Generated by Django 4.2.16 on 2025-01-13 11:15

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_events_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='body',
            field=wagtail.fields.StreamField([('EventQuote', 2), ('EventContentBlocks', 7), ('ProfileBlock', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('quote', 0), ('author', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('image', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StreamBlock', [[('content', 3), ('gallery', 6)]], {}), 8: ('wagtail.blocks.StructBlock', [[('script_title', 0), ('image', 4), ('name', 0), ('position', 0)]], {})}, null=True),
        ),
    ]
