# Generated by Django 4.2.16 on 2025-05-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_events_options_alter_events_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='homepage_featured_event',
            field=models.BooleanField(default=False, verbose_name='Show Featured Event on Homepage'),
        ),
    ]
