# Generated by Django 4.2.16 on 2025-05-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_events_homepage_featured_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='show_details',
            field=models.BooleanField(default=False, verbose_name='Show Details'),
        ),
    ]
