# Generated by Django 4.2.16 on 2025-05-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='button_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='button_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
