# Generated by Django 4.2.16 on 2025-06-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_alter_events_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='release_date',
            field=models.DateField(help_text='The date this event is intended to be publicly announced or made visible (for reference only; does not control visibility).', null=True),
        ),
    ]
