# Generated by Django 4.2.16 on 2025-06-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_events_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='time_label',
            field=models.CharField(blank=True, help_text='Overwrite the default event date label, e.g. Wednesday, 24th November, 1:00 PM – 5:15 PM.', null=True, verbose_name='Custom date label'),
        ),
    ]
