# Generated by Django 4.2.16 on 2025-06-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_alter_events_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='weight',
            field=models.IntegerField(default=100),
        ),
    ]
