# Generated by Django 4.2.16 on 2025-02-03 11:10

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('news', '0002_rename_released_date_news_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'News Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewspageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('script_title', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('background_video_url', models.URLField(blank=True, help_text='mp4 video', null=True, verbose_name='Background video')),
                ('popup_video_url', models.URLField(blank=True, null=True)),
                ('button_label', models.CharField(blank=True, max_length=500, null=True)),
                ('button_url', models.URLField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='newspage_hero', to='news.newsindexpage')),
                ('video_poster_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
