# Generated by Django 4.2.16 on 2025-02-17 08:46

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_news_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=wagtail.fields.StreamField([('HtmlSourceBlock', 2), ('NewsQuoteBlock', 4), ('ContentBlock', 7), ('CTABannerBlock', 9), ('NewsPhotoGalleryBlock', 11), ('NewsProfileBlock', 13), ('SpaceBlock', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'This label is for internal reference only and will not be displayed in the output.', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('block_label', 0), ('source', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('quote', 1), ('author', 3)]], {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('check-list', 'Checklist')], 'required': False}), 6: ('wagtail.blocks.RichTextBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('list_style', 5), ('content', 6), ('css_class', 3)]], {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('image', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('items', 10)]], {}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Profile Picture'}), 13: ('wagtail.blocks.StructBlock', [[('sign', 3), ('image', 12), ('position', 3)]], {}), 14: ('wagtail.blocks.IntegerBlock', (), {'default': 50}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('light-theme', 'Light'), ('dark-theme', 'Dark')], 'label': 'background'}), 16: ('wagtail.blocks.StructBlock', [[('height', 14), ('background', 15)]], {})}, null=True),
        ),
    ]
