# Generated by Django 4.2.16 on 2025-02-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_news_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspagehero',
            name='popup_video_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
