# Generated by Django 4.2.16 on 2025-05-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0062_alter_newsindexpage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
