# Generated by Django 4.2.16 on 2025-05-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0066_alter_news_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
