# Generated by Django 4.2.16 on 2025-05-29 12:39

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0074_alter_newsindexpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=wagtail.fields.StreamField([('HtmlSourceBlock', 2), ('NewsQuoteBlock', 4), ('ContentBlock', 7), ('CTABannerBlock', 9), ('NewsPhotoGalleryBlock', 11), ('NewsProfileBlock', 13), ('SpaceBlock', 16), ('VideoBlock', 23), ('ChildImageBlock', 24), ('LeadParagraphCapsBlock', 25), ('LeadTextBlock', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'This label is for internal reference only and will not be displayed in the output.', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('block_label', 0), ('source', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('quote', 1), ('author', 3)]], {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('check-list', 'Checklist')], 'required': False}), 6: ('wagtail.blocks.RichTextBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('list_style', 5), ('content', 6), ('css_class', 3)]], {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('image', 8)]], {}), 10: ('wagtail.blocks.static_block.StaticBlock', (), {}), 11: ('wagtail.blocks.StructBlock', [[('show_photo_gallery', 10)]], {}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Profile Picture'}), 13: ('wagtail.blocks.StructBlock', [[('sign', 3), ('image', 12), ('position', 3)]], {}), 14: ('wagtail.blocks.IntegerBlock', (), {'default': 50}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('light-theme', 'White'), ('dark-theme', 'Navy'), ('light-teal-theme', 'Light Teal')], 'label': 'Background'}), 16: ('wagtail.blocks.StructBlock', [[('height', 14), ('background', 15)]], {}), 17: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('pt-0', 'No padding'), ('pt-1', '1x'), ('pt-2', '2x'), ('pt-3', '3x'), ('pt-4', '4x'), ('pt-5', '5x')], 'required': False}), 18: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('pb-0', 'No padding'), ('pb-1', '1x'), ('pb-2', '2x'), ('pb-3', '3x'), ('pb-4', '4x'), ('pb-5', '5x')], 'required': False}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('container', 'Container'), ('container-fluid', 'Fullwidth')], 'label': 'layout'}), 20: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 21: ('wagtail.blocks.URLBlock', (), {'help_text': 'MP4 video url'}), 22: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Check to autoplay video without controls overlay.', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('top_padding', 17), ('bottom_padding', 18), ('background', 15), ('layout', 19), ('poster_image', 20), ('video_url', 21), ('autoplay', 22)]], {}), 24: ('wagtail.blocks.StructBlock', [[('image', 8), ('caption', 3)]], {}), 25: ('wagtail.blocks.StructBlock', [[('top_padding', 17), ('bottom_padding', 18), ('background', 15), ('lead_text', 1)]], {}), 26: ('wagtail.blocks.StructBlock', [[('text', 1)]], {})}, null=True),
        ),
    ]
