# Generated by Django 4.2.16 on 2025-05-30 12:31

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0076_newstopcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=500, null=True, populate_from='title')),
                ('weight', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Top Level Category',
                'verbose_name_plural': 'Top Level Categories',
            },
        ),
        migrations.AlterField(
            model_name='newstopcategories',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.topcategory'),
        ),
    ]
