# Generated by Django 4.2.16 on 2024-09-10 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraStyleSettings',
        ),
    ]
