# Generated by Django 4.2.16 on 2024-09-10 05:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=False, help_text='Check to show alert message', verbose_name='Show alert')),
                ('text', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Text')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Global Announcement',
                'verbose_name_plural': 'Global Announcement',
            },
        ),
    ]
