# Generated by Django 4.2.16 on 2025-05-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adminsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalannouncement',
            name='button_label',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='globalannouncement',
            name='button_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalannouncement',
            name='date_label',
            field=models.CharField(max_length=255, null=True, verbose_name='Date and Time label'),
        ),
        migrations.AddField(
            model_name='globalannouncement',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='globalannouncement',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
