# Generated by Django 4.2.16 on 2025-05-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_globalannouncement_button_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalannouncement',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
