# Generated by Django 4.2.16 on 2025-05-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_globalannouncement_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalannouncement',
            name='button_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
