# Generated by Django 4.2.16 on 2025-05-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_globalannouncement_button_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalannouncement',
            name='status',
            field=models.BooleanField(blank=True, default=False, help_text='Check to show alert message', verbose_name='Enable Popup'),
        ),
    ]
