# Generated by Django 4.2.16 on 2025-05-22 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('core', '0009_alter_globalannouncement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalannouncement',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
