# Generated by Django 4.2.16 on 2025-01-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='weight',
            field=models.IntegerField(default=100),
        ),
    ]
