# Generated by Django 4.2.16 on 2025-01-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
