# Generated by Django 4.2.16 on 2025-03-27 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_category_team_catgory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='catgory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='team.category', verbose_name='Category'),
        ),
    ]
