# Generated by Django 4.2.16 on 2025-03-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_team_catgory'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='credentials',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
