# Generated by Django 4.2.16 on 2025-05-14 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_alter_team_options_tutors_instructors_coaches'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coaches',
            options={'verbose_name': 'Coach', 'verbose_name_plural': 'Coaches'},
        ),
        migrations.AlterModelOptions(
            name='instructors',
            options={'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructors'},
        ),
        migrations.AlterModelOptions(
            name='tutors',
            options={'verbose_name': 'Tutor', 'verbose_name_plural': 'Tutors'},
        ),
    ]
