# Generated by Django 4.2.16 on 2025-05-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_alter_coaches_options_alter_instructors_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Leadership Team', 'verbose_name_plural': 'Leadership Team'},
        ),
    ]
