# Generated by Django 4.2.16 on 2025-05-21 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0149_alter_formpage_bottom_body_alter_formpage_top_body_and_more'),
        ('team', '0013_boardmember_linked_page_coaches_linked_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='linked_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.generalpage', verbose_name='Bio Page'),
        ),
        migrations.AlterField(
            model_name='coaches',
            name='linked_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.generalpage', verbose_name='Bio Page'),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='linked_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.generalpage', verbose_name='Bio Page'),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='linked_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.generalpage', verbose_name='Bio Page'),
        ),
    ]
