# Generated by Django 4.2.16 on 2025-05-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_alter_boardmember_linked_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='weight',
            field=models.IntegerField(default=100),
        ),
    ]
