# Generated by Django 4.2.16 on 2024-09-09 09:04

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamiccontentsnippet',
            name='content',
            field=wagtail.fields.StreamField([('HtmlSourceBlock', 2), ('space', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'This label is for internal reference only and will not be displayed in the output.', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('block_label', 0), ('source', 1)]], {}), 3: ('wagtail.blocks.IntegerBlock', (), {'default': 50}), 4: ('wagtail.blocks.StructBlock', [[('height', 3)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='generalpage',
            name='body',
            field=wagtail.fields.StreamField([('HtmlSourceBlock', 2), ('space', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'This label is for internal reference only and will not be displayed in the output.', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('block_label', 0), ('source', 1)]], {}), 3: ('wagtail.blocks.IntegerBlock', (), {'default': 50}), 4: ('wagtail.blocks.StructBlock', [[('height', 3)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='body',
            field=wagtail.fields.StreamField([('HtmlSourceBlock', 2), ('space', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'This label is for internal reference only and will not be displayed in the output.', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('block_label', 0), ('source', 1)]], {}), 3: ('wagtail.blocks.IntegerBlock', (), {'default': 50}), 4: ('wagtail.blocks.StructBlock', [[('height', 3)]], {})}, null=True),
        ),
    ]
