# Generated by Django 4.2.16 on 2024-09-09 09:41

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_dynamiccontentsnippet_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamiccontentsnippet',
            name='content',
            field=wagtail.fields.StreamField([('HtmlSourceBlock', 2), ('space', 4), ('ContentWithVariableWidthBlock', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'This label is for internal reference only and will not be displayed in the output.', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('block_label', 0), ('source', 1)]], {}), 3: ('wagtail.blocks.IntegerBlock', (), {'default': 50}), 4: ('wagtail.blocks.StructBlock', [[('height', 3)]], {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('col-lg-1', 'col-1'), ('col-lg-2', 'col-2'), ('col-lg-3', 'col-3'), ('col-lg-4', 'col-4'), ('col-lg-5', 'col-5'), ('col-lg-6', 'col-6'), ('col-lg-7', 'col-7'), ('col-lg-8', 'col-8'), ('col-lg-9', 'col-9'), ('col-lg-10', 'col-10'), ('col-lg-11', 'col-11'), ('col-lg-12', 'col-12')]}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('offset-lg-1', 'offset-1'), ('offset-lg-2', 'offset-2'), ('offset-lg-3', 'offset-3'), ('offset-lg-4', 'offset-4'), ('offset-lg-5', 'offset-5'), ('offset-lg-6', 'offset-6')], 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('check-list', 'Checklist')], 'required': False}), 8: ('wagtail.blocks.RichTextBlock', (), {}), 9: ('wagtail.blocks.CharBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('list_style', 7), ('content', 8), ('css_class', 9)]], {}), 11: ('wagtail.blocks.StreamBlock', [[('html', 2), ('content', 10), ('space', 4)]], {}), 12: ('wagtail.blocks.StructBlock', [[('column_width', 5), ('column_offset', 6), ('content_blocks', 11), ('css_class', 9)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='generalpage',
            name='body',
            field=wagtail.fields.StreamField([('HtmlSourceBlock', 2), ('space', 4), ('ContentWithVariableWidthBlock', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'This label is for internal reference only and will not be displayed in the output.', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('block_label', 0), ('source', 1)]], {}), 3: ('wagtail.blocks.IntegerBlock', (), {'default': 50}), 4: ('wagtail.blocks.StructBlock', [[('height', 3)]], {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('col-lg-1', 'col-1'), ('col-lg-2', 'col-2'), ('col-lg-3', 'col-3'), ('col-lg-4', 'col-4'), ('col-lg-5', 'col-5'), ('col-lg-6', 'col-6'), ('col-lg-7', 'col-7'), ('col-lg-8', 'col-8'), ('col-lg-9', 'col-9'), ('col-lg-10', 'col-10'), ('col-lg-11', 'col-11'), ('col-lg-12', 'col-12')]}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('offset-lg-1', 'offset-1'), ('offset-lg-2', 'offset-2'), ('offset-lg-3', 'offset-3'), ('offset-lg-4', 'offset-4'), ('offset-lg-5', 'offset-5'), ('offset-lg-6', 'offset-6')], 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('check-list', 'Checklist')], 'required': False}), 8: ('wagtail.blocks.RichTextBlock', (), {}), 9: ('wagtail.blocks.CharBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('list_style', 7), ('content', 8), ('css_class', 9)]], {}), 11: ('wagtail.blocks.StreamBlock', [[('html', 2), ('content', 10), ('space', 4)]], {}), 12: ('wagtail.blocks.StructBlock', [[('column_width', 5), ('column_offset', 6), ('content_blocks', 11), ('css_class', 9)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='body',
            field=wagtail.fields.StreamField([('HtmlSourceBlock', 2), ('space', 4), ('ContentWithVariableWidthBlock', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'This label is for internal reference only and will not be displayed in the output.', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('block_label', 0), ('source', 1)]], {}), 3: ('wagtail.blocks.IntegerBlock', (), {'default': 50}), 4: ('wagtail.blocks.StructBlock', [[('height', 3)]], {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('col-lg-1', 'col-1'), ('col-lg-2', 'col-2'), ('col-lg-3', 'col-3'), ('col-lg-4', 'col-4'), ('col-lg-5', 'col-5'), ('col-lg-6', 'col-6'), ('col-lg-7', 'col-7'), ('col-lg-8', 'col-8'), ('col-lg-9', 'col-9'), ('col-lg-10', 'col-10'), ('col-lg-11', 'col-11'), ('col-lg-12', 'col-12')]}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('offset-lg-1', 'offset-1'), ('offset-lg-2', 'offset-2'), ('offset-lg-3', 'offset-3'), ('offset-lg-4', 'offset-4'), ('offset-lg-5', 'offset-5'), ('offset-lg-6', 'offset-6')], 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('check-list', 'Checklist')], 'required': False}), 8: ('wagtail.blocks.RichTextBlock', (), {}), 9: ('wagtail.blocks.CharBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('list_style', 7), ('content', 8), ('css_class', 9)]], {}), 11: ('wagtail.blocks.StreamBlock', [[('html', 2), ('content', 10), ('space', 4)]], {}), 12: ('wagtail.blocks.StructBlock', [[('column_width', 5), ('column_offset', 6), ('content_blocks', 11), ('css_class', 9)]], {})}, null=True),
        ),
    ]
