# Generated by Django 4.2.16 on 2024-09-10 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('pages', '0006_alter_dynamiccontentsnippet_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraStyleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_css', models.TextField(blank=True, verbose_name='CSS Overrides')),
                ('extra_js', models.TextField(blank=True, verbose_name='JavaScript Overrides')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Global CSS/JS',
                'verbose_name_plural': 'Global CSS/JS',
            },
        ),
    ]
