# Generated by Django 4.2.16 on 2024-09-10 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_extrastylesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraStyleSettings',
        ),
    ]
