# Generated by Django 4.2.16 on 2024-09-10 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_formfield_field_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formpage',
            old_name='thank_you_text',
            new_name='thankyou_message',
        ),
    ]
