# Generated by Django 4.2.16 on 2024-09-12 06:21

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_rename_thank_you_text_formpage_thankyou_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamiccontentsnippet',
            name='content',
            field=wagtail.fields.StreamField([('HtmlSourceBlock', 2), ('CTABannerBlock', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'This label is for internal reference only and will not be displayed in the output.', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('block_label', 0), ('source', 1)]], {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('image', 3)]], {})}, null=True),
        ),
    ]
