# Generated by Django 4.2.16 on 2024-12-24 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('pages', '0016_alter_formpage_bottom_body_alter_formpage_top_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpagehero',
            name='video_poster_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='landingpagehero',
            name='video_poster_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='generalpagehero',
            name='background_video_url',
            field=models.URLField(blank=True, help_text='mp4 video', null=True, verbose_name='Mp4 Video'),
        ),
        migrations.AlterField(
            model_name='landingpagehero',
            name='background_video_url',
            field=models.URLField(blank=True, help_text='mp4 video', null=True, verbose_name='Mp4 Video'),
        ),
    ]
