# Generated by Django 4.2.16 on 2025-01-06 04:53

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_alter_formpage_bottom_body_alter_formpage_top_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamiccontentsnippet',
            name='content',
            field=wagtail.fields.StreamField([('HtmlSourceBlock', 2), ('CTABannerBlock', 4), ('CTAButton', 13), ('CTACardLinksBlock', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'This label is for internal reference only and will not be displayed in the output.', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('block_label', 0), ('source', 1)]], {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('image', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.URLBlock', (), {'required': False}), 9: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'eg. email or phone or #hash', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('page_link', 7), ('external_link', 8), ('document_link', 9), ('free_link', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('text', 6), ('href', 11)]], {}), 13: ('wagtail.blocks.StructBlock', [[('title', 5), ('button', 12)]], {}), 14: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Default backgrund image'}), 15: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Background image'}), 16: ('wagtail.blocks.StructBlock', [[('image', 15), ('icon', 3), ('title', 5), ('text', 1), ('button', 12)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {}), 18: ('wagtail.blocks.StructBlock', [[('image', 14), ('items', 17)]], {})}, null=True),
        ),
    ]
