# Generated by Django 4.2.16 on 2025-01-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0053_alter_formpage_bottom_body_alter_formpage_top_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpagehero',
            name='background_video_url',
            field=models.URLField(blank=True, help_text='mp4 video', null=True, verbose_name='Background video'),
        ),
        migrations.AlterField(
            model_name='generalpagehero',
            name='popup_video_url',
            field=models.URLField(blank=True, help_text='Popup video url', null=True),
        ),
        migrations.AlterField(
            model_name='landingpagehero',
            name='background_video_url',
            field=models.URLField(blank=True, help_text='mp4 video', null=True, verbose_name='Background video'),
        ),
        migrations.AlterField(
            model_name='landingpagehero',
            name='popup_video_url',
            field=models.URLField(blank=True, help_text='Popup video url', null=True),
        ),
    ]
