# Generated by Django 4.2.16 on 2025-01-13 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('pages', '0056_eventpage_eventpagehero'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='hero_script_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='hero_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='EventpageHero',
        ),
    ]
