# Generated by Django 4.2.16 on 2025-02-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0078_alter_formpage_bottom_body_alter_formpage_top_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpagehero',
            name='background_video_url',
            field=models.CharField(blank=True, help_text='mp4 video', max_length=1000, null=True, verbose_name='Background video'),
        ),
        migrations.AlterField(
            model_name='landingpagehero',
            name='background_video_url',
            field=models.CharField(blank=True, help_text='mp4 video', max_length=1000, null=True, verbose_name='Background video'),
        ),
    ]
