# Generated by Django 4.2.16 on 2025-02-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0082_landingpage_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpagehero',
            name='popup_video_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='landingpagehero',
            name='popup_video_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
