# Generated by Django 4.2.16 on 2025-02-18 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('pages', '0084_alter_formpage_bottom_body_alter_formpage_top_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='promo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='promo_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
