# Generated by Django 4.2.16 on 2025-02-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0085_landingpage_promo_image_landingpage_promo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='promo_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
