# Generated by Django 4.2.16 on 2025-03-24 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('pages', '0090_landingpage_promo_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='promo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Menu Promo Page'),
        ),
    ]
