# Generated by Django 4.2.16 on 2025-03-24 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('pages', '0091_alter_landingpage_promo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='promo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='promo_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Menu Promo Page'),
        ),
    ]
