# Generated by Django 4.2.16 on 2025-03-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0099_alter_formpage_bottom_body_alter_formpage_top_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
