# Generated by Django 4.2.16 on 2025-03-27 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('pages', '0100_formpage_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='form_left_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='layout',
            field=models.CharField(choices=[('fullwidth', 'Fullwidth'), ('left-image', 'Form with Left Image')], default='fullwidth', max_length=20),
        ),
    ]
