# Generated by Django 4.2.16 on 2025-05-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0109_alter_formpage_bottom_body_alter_formpage_top_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='after_script_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='before_script_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='script_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
