# Generated by Django 4.2.16 on 2025-05-09 10:59

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0125_alter_formfield_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='help_text',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='help text'),
        ),
    ]
