# Generated by Django 4.2.16 on 2025-05-09 11:49

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0126_alter_formfield_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='help_text_content',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='help text'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='help_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='help text'),
        ),
    ]
