# Generated by Django 4.2.16 on 2025-05-09 12:36

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0127_formfield_help_text_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='help_text_content',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='help text content'),
        ),
    ]
