# Generated by Django 4.2.16 on 2025-05-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0141_alter_formpage_bottom_body_alter_formpage_top_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventpage',
            options={'verbose_name': 'Event Page'},
        ),
    ]
