# Generated by Django 4.2.16 on 2025-05-19 08:58

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('pages', '0142_alter_eventpage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventpageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('script_title', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('background_video_url', models.CharField(blank=True, help_text='mp4 video', max_length=1000, null=True, verbose_name='Background video')),
                ('popup_video_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('button_label', models.CharField(blank=True, max_length=500, null=True)),
                ('button_url', models.URLField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventpage_hero', to='pages.eventpage')),
                ('video_poster_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
