# Generated by Django 4.2.16 on 2025-05-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0147_alter_formpage_bottom_body_alter_formpage_top_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photogallery',
            options={'verbose_name': 'Photo Gallery', 'verbose_name_plural': 'Photo Galleries'},
        ),
    ]
