# Generated by Django 4.2.16 on 2025-05-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0151_alter_formpage_bottom_body_alter_formpage_top_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='layout',
            field=models.CharField(choices=[('fullwidth', 'Fullwidth'), ('left-image', 'Form with Left Image'), ('hide-form', 'Hide Form')], default='fullwidth', max_length=20, verbose_name='Form Layout'),
        ),
    ]
