# Generated by Django 4.2.16 on 2025-06-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0165_portalmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalmenu',
            name='is_external_link',
            field=models.BooleanField(blank=True, default=False, help_text='Check to open link in new window'),
        ),
    ]
