# Generated by Django 4.2.16 on 2025-06-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0166_portalmenu_is_external_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portalmenu',
            options={'verbose_name': 'Portal Item', 'verbose_name_plural': 'Portal Items'},
        ),
    ]
