# Generated by Django 4.2.16 on 2025-06-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0167_alter_portalmenu_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalmenu',
            name='weight',
            field=models.IntegerField(default=100),
        ),
    ]
