# Generated by Django 4.2.16 on 2024-12-31 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('contact', '0002_landingpagehero'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero background image'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hero_title',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='script_title',
            field=models.CharField(null=True),
        ),
        migrations.DeleteModel(
            name='LandingpageHero',
        ),
    ]
