# Generated by Django 4.2.16 on 2025-01-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0020_alter_contactpage_body_alter_contactpage_bottom_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='terms_condition',
            field=models.BooleanField(default=False),
        ),
    ]
