# Generated by Django 4.2.16 on 2025-02-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0049_alter_contactpage_body_alter_contactpage_bottom_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
