# Generated by Django 4.2.16 on 2025-03-27 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('contact', '0061_alter_contactpage_body_alter_contactpage_bottom_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='form_left_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='layout',
            field=models.CharField(choices=[('FullWidth', 'Fullwidth'), ('left-image', 'Form with Left Image')], default='discount', max_length=20),
        ),
    ]
