# Generated by Django 4.2.16 on 2025-03-27 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0062_contactpage_form_left_image_contactpage_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='form_left_image',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='layout',
        ),
    ]
