# Generated by Django 4.2.16 on 2025-05-08 08:55

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('facilityhire', '0002_remove_facilityhireformpage_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityhireformpage',
            name='thankyou_message',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
