# Generated by Django 4.2.16 on 2025-05-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilityhire', '0003_facilityhireformpage_thankyou_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityhireformfield',
            name='field_type',
            field=models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field'), ('image', 'Upload Image'), ('document', 'File Upload'), ('heading', 'Heading')], max_length=16, verbose_name='field type'),
        ),
    ]
