# Generated by Django 4.2.16 on 2025-05-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilityhire', '0005_alter_facilityhireformpage_bottom_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityhireformfield',
            name='help_text',
            field=models.TextField(blank=True, verbose_name='help text'),
        ),
    ]
