# Generated by Django 4.2.16 on 2024-09-09 06:19

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([], blank=True, block_lookup={}, null=True),
        ),
        migrations.CreateModel(
            name='HomepageHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('background_video_url', models.URLField(blank=True, help_text='mp4 video', null=True)),
                ('popup_video_url', models.URLField(blank=True, help_text='embeded video url', null=True)),
                ('button_label', models.CharField(blank=True, max_length=500, null=True)),
                ('button_url', models.URLField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_hero', to='home.homepage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
