# Generated by Django 4.2.16 on 2024-12-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_homepagehero_video_poster_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagehero',
            name='script_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
