# Generated by Django 4.2.16 on 2025-01-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagehero',
            name='primary_tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepagehero',
            name='secondary_tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
