# Generated by Django 4.2.16 on 2025-01-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagehero',
            name='background_video_url',
            field=models.URLField(blank=True, help_text='mp4 video', null=True, verbose_name='Background video'),
        ),
        migrations.AlterField(
            model_name='homepagehero',
            name='popup_video_url',
            field=models.URLField(blank=True, help_text='Popup video url', null=True),
        ),
    ]
