# Generated by Django 4.2.16 on 2025-05-26 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('home', '0125_alter_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='noindex',
            field=models.BooleanField(blank=True, default=False, help_text="Check this to prevent search engines from indexing this page (adds a 'noindex' meta tag).", verbose_name='Exclude from Search Engines'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Thumbnail for Social Sharing'),
        ),
    ]
