# Generated by Django 4.2.16 on 2025-01-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='weight',
            field=models.IntegerField(default=100),
        ),
    ]
